version: '3'

services:





  ticket-order:
    build: ./
    network_mode: host
    ports:
      - "8080:8080"
    restart: always

  ticket-order-db:
    image: mysql
    network_mode: host
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=ticket-order-db"
      - "MYSQL_ROOT_PASSWORD=root"
