version: '3'

services:


  ticket-order:
    image: ticket-order
    network_mode: host
    container_name: ticket-order
    ports:
      - "8080:8080"
    restart: always

  ticket-order-db:
    image: mysql
    network_mode: host
    container_name: ticket-order-db
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=ticket-order-db"
      - "MYSQL_ROOT_PASSWORD=root"
