server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: ticket-order
  datasource:
    url: jdbc:mysql://${ticket-order-db:localhost}:3306/ticket-order-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

app:
  environment:
    ticket-price-host: ${ticket-price-host:localhost}

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: ticket-order
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: raul
    password: raul
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  environment:
    ticket-price-host: none